[package]
name = "final_project"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ply-rs = "0.1.3"
serde_json = "1.0"
serde = "1.0"
rand = "0.8"